### ISSUE TITLE
Support ingesting private repo jobs

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry-github-actions-app#16]
In order to allow using the REST API for private repos, we need a token that has `repo` access (As per the [docs](https://docs.github.com/en/rest/actions/workflow-jobs#get-a-job-for-a-workflow-run)).

```
pdm run ingest https://github.com/getsentry/getsentry/runs/6358404978
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/getsentry/getsentry/actions/jobs/6358404978 HTTP/1.1" 404 None
Traceback (most recent call last):
  File "src/cli.py", line 14, in <module>
    req = get(url)
  File "/Users/armenzg/code/github-actions-app/src/github_sdk.py", line 32, in get
    raise Exception(req.text)
Exception: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/actions#get-a-job-for-a-workflow-run"}
```

**Comment by armenzg** [comment]
I don't know if this issue is still applicable since we have data from one of our private repos. This may have been an issue when using personal access tokens.

**Comment by asottile-sentry** [comment]
yeah this was from the PAT days -- `repo` isn't a scope for apps (they'd get `contents: read` for an installed repository) -- can probably close this one out :tada:
