### ISSUE TITLE
Organizations installing the app should define what DSN to submit to

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry-github-actions-app#37]
Currently, we can only install the app in `getsentry` and all events are sent to a specific Sentry DSN (defined as an env variable).

This will enable other orgs being able to install the app and we submit events on their behalf.

**Comment by armenzg** [comment]
@asottile-sentry I think we could solve this by having the companies interested on this opening a PR and declaring the mapping between their org and which DSN to report to.

Thoughts?

**Comment by asottile-sentry** [comment]
it would probably be better if they committed the DSN to a config file in their repository and then it was read from there?  otherwise we're going to get hundreds of PRs here and acting as a central authority doesn't sound fun

**Comment by asottile-sentry** [comment]
json / ini is simple enough!

**Comment by armenzg** [comment]
The plan as of now:
* Create app that can only be installed under the orgs: armenzg & armenzg-dev
* Create `.sentry` repo with configured DSN
* Install GH App under armenzg-dev and run some CI

**Comment by armenzg** [comment]
I need to change the permission to have access to the single file `sentry_config.ini`.
